# SPDX-FileCopyrightText: 2015 - 2024 Rime community
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
env:
  CI_NAME: Release CI
  SHERPA_ONNX_VERSION: "1.13.2"
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 17
          # will restore cache of dependencies and wrappers
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Install Android NDK
        run: |
          sdkmanager --install "cmake;4.1.2"

      - name: Download sherpa-onnx AAR
        run: |
          mkdir -p app/libs
          curl -fSL -o "app/libs/sherpa-onnx-${SHERPA_ONNX_VERSION}.aar" \
            "https://github.com/k2-fsa/sherpa-onnx/releases/download/v${SHERPA_ONNX_VERSION}/sherpa-onnx-${SHERPA_ONNX_VERSION}.aar"

      - name: Calculate JNI cache hash
        id: cache-hash
        run: |
            ./gradlew :app:calculateNativeCacheHash

      - name: Fetch JNI cache
        uses: actions/cache@v5
        id: jni-cache
        with:
          path: "app/prebuilt"
          key: ${{ runner.os }}-trime-jni-release-${{ steps.cache-hash.outputs.native-cache-hash }}

      - name: Setup Keystore
        run: |
          cat << EOF > keystore.properties
          keyBase64=${{ secrets.SIGNING_KEY }}
          storePassword=${{ secrets.KEY_STORE_PASSWORD }}
          keyAlias=${{ secrets.ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Build Trime
        run: make release

      - name: Add JNI cache
        if: ${{ !steps.jni-cache.outputs.cache-hit }}
        run: cp -R app/build/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib app/prebuilt

      - name: Rename APK
        run: |
          pushd app/build/outputs/apk/release
            for apk in com.carlson.lyraime-v*.apk; do
              arch=$(echo "$apk" | grep -oE '(arm64-v8a|x86_64)')
              ver=$(echo "$apk" | grep -oP 'v\d+\.\d+\.\d+\.\d+')
              mv "$apk" "LyraIME-${arch}-${ver}.apk"
            done
          popd

      - name: Create Stable release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}
          artifacts: "app/build/outputs/apk/release/*.apk"
          body: "Update Version: ${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
